const $=s=>document.querySelector(s),canvas=$('#visualizer'),ctx=canvas.getContext('2d');
const storageKey='miniature-frame-selector-v2';
const state={frames:[],frame:null,frameImage:null,art:null,scale:1,x:0,y:0,drag:null,overlay:false,basket:[]};
const encodePath=s=>s.split('/').map(encodeURIComponent).join('/');
const frameName=f=>(f?.ordering_label||'Unnamed frame').replace(/\.(jpe?g|gif|png)$/i,'');

function readSaved(){try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return {}}}
function persist(){const payload={framePath:state.frame?.path,scale:state.scale,offsetX:state.x,offsetY:state.y,basket:state.basket};try{localStorage.setItem(storageKey,JSON.stringify(payload));return true}catch{return false}}
async function init(){
  const map=await fetch('image-library/catalogue-image-map.json').then(r=>r.json());
  state.frames=map.map(x=>({...x,path:`image-library/${x.family}/${x.local_filename}`}));
  [...new Set(state.frames.map(x=>x.family))].forEach(f=>$('#familyFilter').add(new Option(f.replaceAll('-',' '),f)));
  const saved=readSaved();state.basket=Array.isArray(saved.basket)?saved.basket:[];state.frame=state.frames.find(x=>x.path===saved.framePath)||state.frames[0];
  ['scale','offsetX','offsetY'].forEach(id=>{const key={scale:'scale',offsetX:'x',offsetY:'y'}[id];if(saved[id]!==undefined){$('#'+id).value=saved[id];state[key]=+saved[id]}$('#'+id).addEventListener('input',e=>{state[key]=+e.target.value;render()})});
  $('#familyFilter').onchange=renderGallery;$('#selectFrame').onclick=selectFrame;$('#openReview').onclick=openReview;$('#readyToOrder').onclick=showOrderPanel;$('#contactName').onchange=renderOrderList;
  document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());
  setupInput();renderGallery();updateBasketCount();await loadFrame();updateBuild();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
}
function renderGallery(){const filter=$('#familyFilter').value,g=$('#gallery'),tpl=$('#frameTemplate');g.innerHTML='';state.frames.filter(x=>filter==='all'||x.family===filter).forEach(f=>{const n=tpl.content.cloneNode(true),b=n.querySelector('button'),im=n.querySelector('img');im.src=encodePath(f.path);im.alt=frameName(f);n.querySelector('.tile-label').textContent=frameName(f);n.querySelector('.tile-family').textContent=f.family.replaceAll('-',' ');if(f===state.frame)b.classList.add('selected');b.onclick=async()=>{state.frame=f;persist();await loadFrame();renderGallery();scrollTo({top:0,behavior:'smooth'})};g.append(n)})}
function image(src){return new Promise((yes,no)=>{const i=new Image;i.onload=()=>yes(i);i.onerror=no;i.src=src})}
async function loadFrame(){if(!state.frame)return;state.overlay=false;const raw=await image(encodePath(state.frame.path));const png=state.frame.path.replace(/\.[^.]+$/,'.png');try{state.frameImage=await image(encodePath(png));state.overlay=true}catch{state.frameImage=raw}$('#stageStatus').textContent=`${frameName(state.frame)}${state.overlay?' · overlay':' · reference image'}`;$('#selectFrame').disabled=!state.overlay;render()}
function setupInput(){const choose=e=>{const file=e.target.files[0];if(!file)return;const u=URL.createObjectURL(file);image(u).then(i=>{state.art=i;autoFit(i);URL.revokeObjectURL(u);$('#fitNote').textContent='Auto-fit complete. Drag the artwork or use controls to fine-tune.';render()})};$('#cameraInput').onchange=choose;$('#fileInput').onchange=choose;canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;state.x=Math.max(-1,Math.min(1,state.drag.ox+(e.clientX-state.drag.x)/canvas.clientWidth*2));state.y=Math.max(-1,Math.min(1,state.drag.oy+(e.clientY-state.drag.y)/canvas.clientHeight*2));$('#offsetX').value=state.x;$('#offsetY').value=state.y;render()});canvas.addEventListener('pointerup',()=>state.drag=null)}
function autoFit(img){const sample=document.createElement('canvas');sample.width=80;sample.height=80;const c=sample.getContext('2d');c.drawImage(img,0,0,80,80);const d=c.getImageData(0,0,80,80).data;let minX=80,minY=80,maxX=0,maxY=0;for(let y=0;y<80;y++)for(let x=0;x<80;x++){const p=(y*80+x)*4,bright=(d[p]+d[p+1]+d[p+2])/3;if(d[p+3]>30&&bright<245){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}const ratio=(maxX>minX&&maxY>minY)?Math.max((maxX-minX)/80,(maxY-minY)/80):1;state.scale=Math.max(.8,Math.min(1.8,1/ratio*.88));state.x=0;state.y=0;$('#scale').value=state.scale;$('#offsetX').value=0;$('#offsetY').value=0}
function render(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#111319';ctx.fillRect(0,0,w,h);if(!state.frameImage)return;const fi=state.frameImage,fit=Math.min(w/fi.width,h/fi.height),fw=fi.width*fit,fh=fi.height*fit,fx=(w-fw)/2,fy=(h-fh)/2,ax=fx+fw*.12,ay=fy+fh*.12,aw=fw*.76,ah=fh*.76;if(state.art){const a=state.art,base=Math.max(aw/a.width,ah/a.height)*state.scale,dw=a.width*base,dh=a.height*base;ctx.drawImage(a,ax+(aw-dw)/2+state.x*aw*.35,ay+(ah-dh)/2+state.y*ah*.35,dw,dh)}ctx.drawImage(fi,fx,fy,fw,fh)}
function snapshot(){const shot=document.createElement('canvas');shot.width=560;shot.height=560;shot.getContext('2d').drawImage(canvas,0,0,560,560);return shot.toDataURL('image/jpeg',.82)}
function selectFrame(){const note=$('#selectionNote');if(!state.art){note.textContent='Add your painting before selecting a frame.';return}if(!state.overlay){note.textContent='This catalogue image is a reference, not a usable frame overlay.';return}const width=$('#apertureWidth').value.trim(),height=$('#apertureHeight').value.trim();const item={id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,framePath:state.frame.path,name:frameName(state.frame),family:state.frame.family,requiredWidth:width,requiredHeight:height,imageWidth:state.frameImage.naturalWidth,imageHeight:state.frameImage.naturalHeight,thumbnail:snapshot(),selectedAt:Date.now()};state.basket.push(item);if(!persist()){state.basket.pop();note.textContent='Device storage is full. Remove an older selection and try again.';return}updateBasketCount();note.textContent=`${item.name} added to your review.`}
function updateBasketCount(){$('#basketCount').textContent=state.basket.length}
function dimensions(item){return item.requiredWidth&&item.requiredHeight?`Required aperture: ${item.requiredWidth} × ${item.requiredHeight} mm`:'Required aperture: not entered'}
function openReview(){renderReview();$('#orderPanel').hidden=true;$('#reviewDialog').showModal()}
function renderReview(){const list=$('#reviewList');list.innerHTML='';$('#reviewEmpty').hidden=state.basket.length>0;$('#readyToOrder').hidden=state.basket.length===0;state.basket.forEach(item=>{const card=document.createElement('article');card.className='review-card';const thumb=document.createElement('button');thumb.className='review-thumb';thumb.setAttribute('aria-label',`Preview ${item.name}`);const thumbImage=document.createElement('img');thumbImage.alt='';thumbImage.src=item.thumbnail;thumb.append(thumbImage);thumb.onclick=()=>openLargePreview(item);const text=document.createElement('div'),name=document.createElement('div'),size=document.createElement('div'),pixels=document.createElement('div');name.className='review-name';name.textContent=item.name;size.className='review-meta';size.textContent=dimensions(item);pixels.className='review-meta';pixels.textContent=`Overlay image: ${item.imageWidth} × ${item.imageHeight} px`;text.append(name,size,pixels);const remove=document.createElement('button');remove.className='remove-button';remove.textContent='×';remove.setAttribute('aria-label',`Remove ${item.name}`);remove.onclick=()=>removeSelection(item.id);card.append(thumb,text,remove);list.append(card)})}
function removeSelection(id){state.basket=state.basket.filter(item=>item.id!==id);if(!state.basket.length)$('#orderPanel').hidden=true;persist();updateBasketCount();renderReview();renderOrderList()}
function openLargePreview(item){$('#largePreview').src=item.thumbnail;$('#largePreview').alt=`${item.name} framed preview`;$('#largePreviewCaption').textContent=`${item.name} · ${dimensions(item)}`;$('#previewDialog').showModal()}
function showOrderPanel(){$('#orderPanel').hidden=false;renderOrderList();$('#orderPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function renderOrderList(){const contact=$('#contactName').value,list=$('#orderList');list.innerHTML='';const intro=document.createElement('div');intro.className='order-line';intro.textContent=contact==='Other'?'Ask for the person handling miniature-frame orders.':`Ask for ${contact}.`;list.append(intro);state.basket.forEach((item,index)=>{const line=document.createElement('div');line.className='order-line';line.textContent=`${index+1}. ${item.name} — ${dimensions(item).replace('Required aperture: ','')}`;list.append(line)})}
async function updateBuild(){try{const r=await fetch('https://api.github.com/repos/sourmilkman/frame-selector/commits/main',{cache:'no-store'}).then(x=>x.json());$('#build').textContent=`BUILD · ${r.sha.slice(0,7)}`}catch{$('#build').textContent='BUILD · LOCAL'}}
init().catch(e=>{$('#stageStatus').textContent='Library could not load';console.error(e)});
