const $=s=>document.querySelector(s),canvas=$('#visualizer'),ctx=canvas.getContext('2d');
const storageKey='miniature-frame-selector-v2';
const state={frames:[],frame:null,frameImage:null,art:null,scale:1,x:0,y:0,drag:null,locked:false,overlay:false,frameOptionIndex:0,basket:[]};
const pricing=window.FRAME_PRICING||{items:{},postage:5.50,checked:'Unavailable'};
const encodePath=s=>s.split('/').map(encodeURIComponent).join('/');
const bareName=value=>(value||'Unnamed frame').replace(/\.(jpe?g|gif|png)$/i,'');
const pricingKey=(family,filename)=>`${family}/${bareName(filename)}`.toLowerCase();
const framePrice=f=>pricing.items[pricingKey(f?.family,f?.local_filename)];
const frameName=f=>framePrice(f)?.name||bareName(f?.ordering_label);
const itemPrice=item=>pricing.items[item.pricingKey||pricingKey(item.family,item.framePath?.split('/').pop())];
const selectedOption=item=>{const product=itemPrice(item);return product?.options?.[Math.max(0,Math.min(product.options.length-1,Number(item.optionIndex)||0))]};
const money=value=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(value||0);

function readSaved(){try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return {}}}
function persist(){const payload={framePath:state.frame?.path,scale:state.scale,offsetX:state.x,offsetY:state.y,frameOptionIndex:state.frameOptionIndex,basket:state.basket};try{localStorage.setItem(storageKey,JSON.stringify(payload));return true}catch{return false}}
async function init(){
  const map=await fetch('image-library/catalogue-image-map.json').then(r=>r.json());
  state.frames=map.map(x=>({...x,path:`image-library/${x.family}/${x.local_filename}`}));
  [...new Set(state.frames.map(x=>x.family))].forEach(f=>$('#familyFilter').add(new Option(f.replaceAll('-',' '),f)));
  const saved=readSaved();state.basket=Array.isArray(saved.basket)?saved.basket:[];state.frame=state.frames.find(x=>x.path===saved.framePath)||state.frames[0];state.frameOptionIndex=Math.max(0,Number(saved.frameOptionIndex)||0);
  ['scale','offsetX','offsetY'].forEach(id=>{const key={scale:'scale',offsetX:'x',offsetY:'y'}[id];if(saved[id]!==undefined){$('#'+id).value=saved[id];state[key]=+saved[id]}$('#'+id).addEventListener('input',e=>{state[key]=+e.target.value;render()})});
  $('#familyFilter').onchange=renderGallery;$('#frameOption').onchange=e=>{state.frameOptionIndex=Number(e.target.value);persist()};$('#lockImage').onclick=toggleLock;$('#selectFrame').onclick=selectFrame;$('#openReview').onclick=openReview;$('#readyToOrder').onclick=showOrderPanel;
  document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());
  setupInput();setLocked(false);renderGallery();updateBasketCount();await loadFrame();updateBuild();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
}
function renderGallery(){const filter=$('#familyFilter').value,g=$('#gallery'),tpl=$('#frameTemplate');g.innerHTML='';state.frames.filter(x=>filter==='all'||x.family===filter).forEach(f=>{const n=tpl.content.cloneNode(true),b=n.querySelector('button'),im=n.querySelector('img');im.src=encodePath(f.path);im.alt=frameName(f);n.querySelector('.tile-label').textContent=frameName(f);n.querySelector('.tile-family').textContent=f.family.replaceAll('-',' ');if(f===state.frame)b.classList.add('selected');b.onclick=async()=>{if(f!==state.frame){state.frameOptionIndex=0;setLocked(false)}state.frame=f;persist();await loadFrame();renderGallery();scrollTo({top:0,behavior:'smooth'})};g.append(n)})}
function image(src){return new Promise((yes,no)=>{const i=new Image;i.onload=()=>yes(i);i.onerror=no;i.src=src})}
async function loadFrame(){if(!state.frame)return;state.overlay=false;const raw=await image(encodePath(state.frame.path));const png=state.frame.path.replace(/\.[^.]+$/,'.png');try{state.frameImage=await image(encodePath(png));state.overlay=true}catch{state.frameImage=raw}const product=framePrice(state.frame),status=product?.unavailable?' · unavailable':state.overlay?' · overlay':' · reference image';$('#stageStatus').textContent=`${frameName(state.frame)}${status}`;$('#selectFrame').disabled=!state.overlay||!product||product.unavailable;$('#selectionNote').textContent=product?.unavailable?(product.note||'Unavailable from the supplier.'):' ';renderFrameOptions();render()}
function renderFrameOptions(){const product=framePrice(state.frame),field=$('#frameOptionField'),select=$('#frameOption'),available=state.overlay&&product&&!product.unavailable&&product.options?.length;select.innerHTML='';field.hidden=!available;if(!available)return;state.frameOptionIndex=Math.max(0,Math.min(product.options.length-1,Number(state.frameOptionIndex)||0));product.options.forEach((entry,index)=>select.add(new Option(`${entry.code} · ${entry.glass} · ${money(entry.price)}`,index)));select.value=String(state.frameOptionIndex)}
function setLocked(value){state.locked=Boolean(value)&&Boolean(state.art);state.drag=null;const button=$('#lockImage');button.disabled=!state.art;button.setAttribute('aria-pressed',String(state.locked));button.textContent=state.locked?'Image locked':'Lock image in place';button.classList.toggle('locked',state.locked);canvas.classList.toggle('locked',state.locked);['scale','offsetX','offsetY'].forEach(id=>$('#'+id).disabled=state.locked);if(state.art)$('#fitNote').textContent=state.locked?'Image position locked. Choose another frame to unlock it.':'Auto-fit complete. Drag the artwork or use controls to fine-tune.'}
function toggleLock(){if(!state.art){$('#selectionNote').textContent='Add your painting before locking it.';return}setLocked(!state.locked);$('#selectionNote').textContent=state.locked?'Image position locked.':'Image position unlocked.'}
function setupInput(){const choose=e=>{const file=e.target.files[0];if(!file)return;const u=URL.createObjectURL(file);image(u).then(i=>{state.art=i;autoFit(i);setLocked(false);URL.revokeObjectURL(u);render()})};$('#cameraInput').onchange=choose;$('#fileInput').onchange=choose;canvas.addEventListener('pointerdown',e=>{if(state.locked)return;state.drag={x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(state.locked||!state.drag)return;state.x=Math.max(-1,Math.min(1,state.drag.ox+(e.clientX-state.drag.x)/canvas.clientWidth*2));state.y=Math.max(-1,Math.min(1,state.drag.oy+(e.clientY-state.drag.y)/canvas.clientHeight*2));$('#offsetX').value=state.x;$('#offsetY').value=state.y;render()});canvas.addEventListener('pointerup',()=>state.drag=null)}
function autoFit(img){const sample=document.createElement('canvas');sample.width=80;sample.height=80;const c=sample.getContext('2d');c.drawImage(img,0,0,80,80);const d=c.getImageData(0,0,80,80).data;let minX=80,minY=80,maxX=0,maxY=0;for(let y=0;y<80;y++)for(let x=0;x<80;x++){const p=(y*80+x)*4,bright=(d[p]+d[p+1]+d[p+2])/3;if(d[p+3]>30&&bright<245){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}const ratio=(maxX>minX&&maxY>minY)?Math.max((maxX-minX)/80,(maxY-minY)/80):1;state.scale=Math.max(.8,Math.min(1.8,1/ratio*.88));state.x=0;state.y=0;$('#scale').value=state.scale;$('#offsetX').value=0;$('#offsetY').value=0}
function render(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#111319';ctx.fillRect(0,0,w,h);if(!state.frameImage)return;const fi=state.frameImage,fit=Math.min(w/fi.width,h/fi.height),fw=fi.width*fit,fh=fi.height*fit,fx=(w-fw)/2,fy=(h-fh)/2,ax=fx+fw*.12,ay=fy+fh*.12,aw=fw*.76,ah=fh*.76;if(state.art){const a=state.art,base=Math.max(aw/a.width,ah/a.height)*state.scale,dw=a.width*base,dh=a.height*base;ctx.drawImage(a,ax+(aw-dw)/2+state.x*aw*.35,ay+(ah-dh)/2+state.y*ah*.35,dw,dh)}ctx.drawImage(fi,fx,fy,fw,fh)}
function snapshot(){const shot=document.createElement('canvas');shot.width=560;shot.height=560;shot.getContext('2d').drawImage(canvas,0,0,560,560);return shot.toDataURL('image/jpeg',.82)}
function selectFrame(){const note=$('#selectionNote'),product=framePrice(state.frame);if(!state.art){note.textContent='Add your painting before selecting a frame.';return}if(!state.overlay){note.textContent='This catalogue image is a reference, not a usable frame overlay.';return}if(!product||product.unavailable){note.textContent=product?.note||'Current supplier pricing is unavailable for this frame.';return}const width=$('#apertureWidth').value.trim(),height=$('#apertureHeight').value.trim();const item={id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,framePath:state.frame.path,pricingKey:pricingKey(state.frame.family,state.frame.local_filename),name:product.name,family:state.frame.family,requiredWidth:width,requiredHeight:height,optionIndex:state.frameOptionIndex,quantity:1,thumbnail:snapshot(),selectedAt:Date.now()};state.basket.push(item);if(!persist()){state.basket.pop();note.textContent='Device storage is full. Remove an older selection and try again.';return}updateBasketCount();note.textContent=`${item.name} added to your review.`}
function updateBasketCount(){$('#basketCount').textContent=state.basket.length}
function dimensions(item){return item.requiredWidth&&item.requiredHeight?`Required aperture: ${item.requiredWidth} × ${item.requiredHeight} mm`:'Required aperture: not entered'}
function openReview(){renderReview();$('#orderPanel').hidden=true;$('#reviewDialog').showModal()}
function renderReview(){const list=$('#reviewList');list.innerHTML='';$('#reviewEmpty').hidden=state.basket.length>0;state.basket.forEach(item=>{const product=itemPrice(item),option=selectedOption(item),card=document.createElement('article');card.className='review-card';const thumb=document.createElement('button');thumb.className='review-thumb';thumb.setAttribute('aria-label',`Preview ${product?.name||item.name}`);const thumbImage=document.createElement('img');thumbImage.alt='';thumbImage.src=item.thumbnail;thumb.append(thumbImage);thumb.onclick=()=>openLargePreview(item);const text=document.createElement('div');text.className='review-content';const name=document.createElement('div');name.className='review-name';name.textContent=product?.name||item.name;const size=document.createElement('div');size.className='review-meta';size.textContent=dimensions(item);text.append(name,size);if(product?.unavailable||!product?.options?.length){const unavailable=document.createElement('div');unavailable.className='unavailable-note';unavailable.textContent=product?.note||'Current price unavailable';text.append(unavailable)}else{const optionLabel=document.createElement('label');optionLabel.className='review-field';optionLabel.textContent='Frame option';const select=document.createElement('select');product.options.forEach((entry,index)=>select.add(new Option(`${entry.code} · ${entry.glass} · ${money(entry.price)}`,index)));select.value=String(Math.max(0,Math.min(product.options.length-1,Number(item.optionIndex)||0)));select.onchange=()=>{item.optionIndex=Number(select.value);persist();renderReview();renderOrderList()};optionLabel.append(select);const quantityLabel=document.createElement('label');quantityLabel.className='review-field quantity-field';quantityLabel.textContent='Quantity';const quantity=document.createElement('input');quantity.type='number';quantity.inputMode='numeric';quantity.min='1';quantity.max='99';quantity.step='1';quantity.value=String(Math.max(1,Number(item.quantity)||1));quantity.onchange=()=>{item.quantity=Math.max(1,Math.min(99,Math.round(Number(quantity.value)||1)));persist();renderReview();renderOrderList()};quantityLabel.append(quantity);const line=document.createElement('div');line.className='line-total';line.textContent=`${option.code} · Glass ${option.glass} · ${money(option.price*(Number(item.quantity)||1))}`;text.append(optionLabel,quantityLabel,line)}const remove=document.createElement('button');remove.className='remove-button';remove.textContent='×';remove.setAttribute('aria-label',`Remove ${product?.name||item.name}`);remove.onclick=()=>removeSelection(item.id);card.append(thumb,text,remove);list.append(card)});renderTotals()}
function removeSelection(id){state.basket=state.basket.filter(item=>item.id!==id);if(!state.basket.length)$('#orderPanel').hidden=true;persist();updateBasketCount();renderReview();renderOrderList()}
function openLargePreview(item){const name=itemPrice(item)?.name||item.name;$('#largePreview').src=item.thumbnail;$('#largePreview').alt=`${name} framed preview`;$('#largePreviewCaption').textContent=`${name} · ${dimensions(item)}`;$('#previewDialog').showModal()}
function showOrderPanel(){$('#orderPanel').hidden=false;renderOrderList();$('#orderPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function totals(){const subtotal=state.basket.reduce((sum,item)=>{const option=selectedOption(item),product=itemPrice(item);return sum+(!option||product?.unavailable?0:option.price*Math.max(1,Number(item.quantity)||1))},0);return{subtotal,postage:subtotal?pricing.postage:0,total:subtotal+(subtotal?pricing.postage:0)}}
function renderTotals(){const values=totals();$('#reviewTotals').hidden=!state.basket.length;$('#subtotal').textContent=money(values.subtotal);$('#postage').textContent=money(values.postage);$('#grandTotal').textContent=money(values.total);$('#readyToOrder').hidden=!values.subtotal}
function renderOrderList(){const list=$('#orderList');list.innerHTML='';state.basket.forEach((item,index)=>{const product=itemPrice(item),option=selectedOption(item);if(!option||product?.unavailable)return;const quantity=Math.max(1,Number(item.quantity)||1),line=document.createElement('div');line.className='order-line';line.textContent=`${index+1}. ${product.name} · ${option.code} · Glass ${option.glass} · ${quantity} × ${money(option.price)} = ${money(quantity*option.price)}`;list.append(line)});const values=totals(),summary=document.createElement('div');summary.className='order-line order-summary';summary.textContent=`Subtotal ${money(values.subtotal)} · UK P&P ${money(values.postage)} · Total ${money(values.total)}`;list.append(summary)}
async function updateBuild(){try{const r=await fetch('https://api.github.com/repos/sourmilkman/frame-selector/commits/main',{cache:'no-store'}).then(x=>x.json());$('#build').textContent=`BUILD · ${r.sha.slice(0,7)}`}catch{$('#build').textContent='BUILD · LOCAL'}}
init().catch(e=>{$('#stageStatus').textContent='Library could not load';console.error(e)});
