const $=s=>document.querySelector(s), canvas=$('#visualizer'),ctx=canvas.getContext('2d');
const state={frames:[],frame:null,art:null,scale:1,x:0,y:0,drag:null,overlay:false};
const storageKey='miniature-frame-selector-v1';
const encodePath=s=>s.split('/').map(encodeURIComponent).join('/');

async function init(){
  const map=await fetch('image-library/catalogue-image-map.json').then(r=>r.json());
  state.frames=map.map(x=>({...x,path:`image-library/${x.family}/${x.local_filename}`}));
  const families=[...new Set(state.frames.map(x=>x.family))];
  families.forEach(f=>$('#familyFilter').add(new Option(f.replaceAll('-',' '),f)));
  const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');
  state.frame=state.frames.find(x=>x.path===saved.framePath)||state.frames[0];
  ['scale','offsetX','offsetY'].forEach(id=>{if(saved[id]!==undefined){$('#'+id).value=saved[id];state[{scale:'scale',offsetX:'x',offsetY:'y'}[id]]=+saved[id]} $('#'+id).addEventListener('input',e=>{state[{scale:'scale',offsetX:'x',offsetY:'y'}[id]]=+e.target.value;render()})});
  $('#familyFilter').onchange=renderGallery; $('#saveSelection').onclick=save; setupInput(); renderGallery(); await loadFrame(); updateBuild();
}
function renderGallery(){const filter=$('#familyFilter').value,g=$('#gallery'),tpl=$('#frameTemplate');g.innerHTML='';state.frames.filter(x=>filter==='all'||x.family===filter).forEach(f=>{const n=tpl.content.cloneNode(true),b=n.querySelector('button'),im=n.querySelector('img');im.src=encodePath(f.path);im.alt=f.ordering_label;n.querySelector('.tile-label').textContent=f.ordering_label;n.querySelector('.tile-family').textContent=f.family.replaceAll('-',' ');if(f===state.frame)b.classList.add('selected');b.onclick=async()=>{state.frame=f;await loadFrame();renderGallery()};g.append(n)})}
function image(src){return new Promise((yes,no)=>{const i=new Image;i.onload=()=>yes(i);i.onerror=no;i.src=src})}
async function loadFrame(){if(!state.frame)return;state.overlay=false;const raw=await image(encodePath(state.frame.path));const png=state.frame.path.replace(/\.[^.]+$/,'.png');try{state.frameImage=await image(encodePath(png));state.overlay=true}catch{state.frameImage=raw}$('#stageStatus').textContent=`${state.frame.ordering_label}${state.overlay?' · overlay':''}`;render()}
function setupInput(){const choose=e=>{const file=e.target.files[0];if(!file)return;const u=URL.createObjectURL(file);image(u).then(i=>{state.art=i;autoFit(i);URL.revokeObjectURL(u);$('#fitNote').textContent='Auto-fit complete. Drag the artwork or use controls to fine-tune.';render()})};$('#cameraInput').onchange=choose;$('#fileInput').onchange=choose;canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;state.x=Math.max(-1,Math.min(1,state.drag.ox+(e.clientX-state.drag.x)/canvas.clientWidth*2));state.y=Math.max(-1,Math.min(1,state.drag.oy+(e.clientY-state.drag.y)/canvas.clientHeight*2));$('#offsetX').value=state.x;$('#offsetY').value=state.y;render()});canvas.addEventListener('pointerup',()=>state.drag=null)}
function autoFit(img){const sample=document.createElement('canvas');sample.width=80;sample.height=80;const c=sample.getContext('2d');c.drawImage(img,0,0,80,80);const d=c.getImageData(0,0,80,80).data;let minX=80,minY=80,maxX=0,maxY=0;for(let y=0;y<80;y++)for(let x=0;x<80;x++){const p=(y*80+x)*4,bright=(d[p]+d[p+1]+d[p+2])/3;if(d[p+3]>30&&bright<245){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}const ratio=(maxX>minX&&maxY>minY)?Math.max((maxX-minX)/80,(maxY-minY)/80):1;state.scale=Math.max(.8,Math.min(1.8,1/ratio*.88));state.x=0;state.y=0;$('#scale').value=state.scale;$('#offsetX').value=0;$('#offsetY').value=0}
function render(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#111319';ctx.fillRect(0,0,w,h);if(!state.frameImage)return;const fi=state.frameImage,fit=Math.min(w/fi.width,h/fi.height),fw=fi.width*fit,fh=fi.height*fit,fx=(w-fw)/2,fy=(h-fh)/2;const ax=fx+fw*.16,ay=fy+fh*.19,aw=fw*.68,ah=fh*.62;if(state.art){ctx.save();ctx.beginPath();ctx.roundRect(ax,ay,aw,ah,Math.min(18,aw*.04));ctx.clip();const a=state.art,base=Math.max(aw/a.width,ah/a.height)*state.scale,dw=a.width*base,dh=a.height*base;ctx.drawImage(a,ax+(aw-dw)/2+state.x*aw*.35,ay+(ah-dh)/2+state.y*ah*.35,dw,dh);ctx.restore()}if(state.overlay)ctx.drawImage(fi,fx,fy,fw,fh);else{ctx.drawImage(fi,fx,fy,fw,fh);if(state.art){ctx.save();ctx.beginPath();ctx.roundRect(ax,ay,aw,ah,Math.min(18,aw*.04));ctx.clip();const a=state.art,base=Math.max(aw/a.width,ah/a.height)*state.scale,dw=a.width*base,dh=a.height*base;ctx.drawImage(a,ax+(aw-dw)/2+state.x*aw*.35,ay+(ah-dh)/2+state.y*ah*.35,dw,dh);ctx.restore()}}}
function save(){localStorage.setItem(storageKey,JSON.stringify({framePath:state.frame.path,scale:state.scale,offsetX:state.x,offsetY:state.y}));$('#saveSelection').textContent='Saved on this device';setTimeout(()=>$('#saveSelection').textContent='Save selection on this device',1600)}
async function updateBuild(){try{const r=await fetch('https://api.github.com/repos/sourmilkman/frame-selector/commits/main',{cache:'no-store'}).then(x=>x.json());$('#build').textContent=`BUILD · ${r.sha.slice(0,7)}`}catch{$('#build').textContent='BUILD · LOCAL'}}
init().catch(e=>{$('#stageStatus').textContent='Library could not load';console.error(e)});
